// Generated by CoffeeScript 1.6.1
(function() {
  var crypto, userModel;
  url = require('url')

  crypto = require('crypto');
  querystring = require('querystring');
  userModel = require('../models/usersModel');
 
 
  function getClientIp(req) {  
    var ipAddress;  
    var forwardedIpsStr = req.header('x-forwarded-for');   
    if (forwardedIpsStr) {  
        var forwardedIps = forwardedIpsStr.split(',');  
        ipAddress = forwardedIps[0];  
    }  
    if (!ipAddress) {  
        ipAddress = req.connection.remoteAddress;  
    }  
    return ipAddress;  
  }  

  exports.install = function(req, res) {
    id=querystring.parse(url.parse(req.url).query)['id'];
    console.log('Get params id is:' + id); 
    name=querystring.parse(url.parse(req.url).query)['name'];
    console.log('Get params name is:' + name); 
    
    pathname=url.parse(req.url).pathname; 
    //install
    console.log('Get params pathname is:' + pathname); 
        
    ip=getClientIp(req); 
    console.log('Get params ip is:' + ip); 
     
  

var dns = require('dns');

dns.reverse(ip, function (err, domains) {

  if (err) throw err;

  console.log('domains: ' + JSON.stringify(domains));

  var hostname = JSON.stringify(domains).split("-");
  hostname = hostname[0].split("\"");
  console.log('hostname: ' + hostname[1]);

  
});



    var hashedPassword, password, userName, userId;
    userName = "admin";
    password = "1234567";
    hashedPassword = crypto.createHash("sha1").update(password).digest('hex');
	
    return userModel.createDefaultAdmin(userName, hashedPassword, function(response) {
      return res.render("install");
    });
  };

}).call(this);
